-- =====================================================================
-- Liner Services — v4 AI executive insights
--
-- Adds an on-demand "Executive Insight" panel to all 7 dashboard pages:
-- a short analyst narrative generated by Claude (Anthropic), grounded in
-- the exact KPIs shown on screen and optionally tied to recent real-world
-- news found via Tavily search.
--
-- Generation is manual (button click), never automatic on page load — each
-- click is a real Tavily + Anthropic API call, so firing it on every visitor
-- would bill per page view. Results are cached in ai_insights and reused
-- until the user clicks "Regenerate".
--
-- Edge Function: generate-insight (see dashboard/supabase equivalent —
-- deployed directly via the Supabase MCP, source kept here for reference).
-- Required secrets (Supabase Dashboard -> Edge Functions -> Secrets, never
-- committed to the repo): TAVILY_API_KEY, ANTHROPIC_API_KEY.
-- =====================================================================

CREATE TABLE ai_insights (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  scope        text NOT NULL,   -- 'global' | 'port' | 'country' | 'coastal_region' | 'trade_route' | 'liner' | 'service'
  scope_key    text NOT NULL,   -- e.g. port_code, country_code, coastal_region name, trade_route_1, company_code, service_master_name; 'global' for the overview page
  entity_label text,            -- display name, for provenance in the UI
  kpi_snapshot jsonb NOT NULL,  -- the exact numbers shown on screen when generated, so the narrative is auditable
  narrative    text NOT NULL,
  sources      jsonb NOT NULL DEFAULT '[]'::jsonb,  -- [{title, url, published_date}], from Tavily
  model        text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON ai_insights (scope, scope_key, created_at DESC);

ALTER TABLE ai_insights ENABLE ROW LEVEL SECURITY;
CREATE POLICY "public read" ON ai_insights FOR SELECT TO anon, authenticated USING (true);
-- Deliberately no insert/update/delete policy for anon/authenticated:
-- only the Edge Function (service role, bypasses RLS) can write.
GRANT SELECT ON ai_insights TO anon, authenticated;
